spring.application.name=hospy

# Server configuration
server.port=8080

# PostgreSQL Database Configuration (RENDER - RED EXTERNA SEGURA)
spring.datasource.url=jdbc:postgresql://dpg-d7i32pnavr4c73fdkci0-a.oregon-postgres.render.com:5432/hospital_l0or?sslmode=require
spring.datasource.username=hospital_l0or_user
spring.datasource.password=V9NVq474a0ZMg2glukhEFJMEnsqTFOkh
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Views Cache (Desactivado para desarrollo)
spring.thymeleaf.cache=false
