spring.application.name=hospy

# Server configuration
server.port=8080

# H2 Database Configuration (TEMPORAL PARA QUE EL PROGRAMA FUNCIONE YA)
spring.datasource.url=jdbc:h2:mem:hospitaldb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Views Cache (Desactivado para desarrollo)
spring.thymeleaf.cache=false
